import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  apisidebar: [
    {
      type: "doc",
      id: "rskj/rskj-json-rpc",
    },
    {
      type: "doc",
      id: "json-rpc-protocol",
      label: "JSON-RPC protocol",
    },
    {
      type: "category",
      label: "eth",
      items: [
        {
          type: "doc",
          id: "rskj/eth-block-number",
          label: "eth_blockNumber",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rskj/eth-call",
          label: "eth_call",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rskj/eth-chain-id",
          label: "eth_chainId",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rskj/eth-coinbase",
          label: "eth_coinbase",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rskj/eth-estimate-gas",
          label: "eth_estimateGas",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rskj/eth-gas-price",
          label: "eth_gasPrice",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rskj/eth-get-balance",
          label: "eth_getBalance",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rskj/eth-get-block-by-hash",
          label: "eth_getBlockByHash",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rskj/eth-get-block-by-number",
          label: "eth_getBlockByNumber",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rskj/eth-get-block-transaction-count-by-hash",
          label: "eth_getBlockTransactionCountByHash",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rskj/eth-get-block-transaction-count-by-number",
          label: "eth_getBlockTransactionCountByNumber",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rskj/eth-get-code",
          label: "eth_getCode",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rskj/eth-get-filter-changes",
          label: "eth_getFilterChanges",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rskj/eth-get-filter-logs",
          label: "eth_getFilterLogs",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rskj/eth-get-logs",
          label: "eth_getLogs",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rskj/eth-get-storage-at",
          label: "eth_getStorageAt",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rskj/eth-get-transaction-by-block-hash-and-index",
          label: "eth_getTransactionByBlockHashAndIndex",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rskj/eth-get-transaction-by-block-number-and-index",
          label: "eth_getTransactionByBlockNumberAndIndex",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rskj/eth-get-transaction-by-hash",
          label: "eth_getTransactionByHash",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rskj/eth-get-transaction-count",
          label: "eth_getTransactionCount",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rskj/eth-get-transaction-receipt",
          label: "eth_getTransactionReceipt",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rskj/eth-get-uncle-by-block-hash-and-index",
          label: "eth_getUncleByBlockHashAndIndex",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rskj/eth-get-uncle-by-block-number-and-index",
          label: "eth_getUncleByBlockNumberAndIndex",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rskj/eth-get-uncle-count-by-block-hash",
          label: "eth_getUncleCountByBlockHash",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rskj/eth-get-uncle-count-by-block-number",
          label: "eth_getUncleCountByBlockNumber",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rskj/eth-hashrate",
          label: "eth_hashrate",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rskj/eth-mining",
          label: "eth_mining",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rskj/eth-new-block-filter",
          label: "eth_newBlockFilter",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rskj/eth-new-filter",
          label: "eth_newFilter",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rskj/eth-new-pending-transaction-filter",
          label: "eth_newPendingTransactionFilter",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rskj/eth-protocol-version",
          label: "eth_protocolVersion",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rskj/eth-send-raw-transaction",
          label: "eth_sendRawTransaction",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rskj/eth-send-transaction",
          label: "eth_sendTransaction",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rskj/eth-sign",
          label: "eth_sign",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rskj/eth-syncing",
          label: "eth_syncing",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rskj/eth-uninstall-filter",
          label: "eth_uninstallFilter",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "mnr",
      items: [
        {
          type: "doc",
          id: "rskj/mnr-get-work",
          label: "mnr_getWork",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rskj/mnr-submit-work",
          label: "mnr_submitWork",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "net",
      items: [
        {
          type: "doc",
          id: "rskj/net-listening",
          label: "net_listening",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rskj/net-peer-count",
          label: "net_peerCount",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rskj/net-peer-list",
          label: "net_peerList",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rskj/net-version",
          label: "net_version",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "sco",
      items: [
        {
          type: "doc",
          id: "rskj/sco-ban-address",
          label: "sco_banAddress",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rskj/sco-banned-addresses",
          label: "sco_bannedAddresses",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rskj/sco-clear-peer-scoring",
          label: "sco_clearPeerScoring",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rskj/sco-peer-list",
          label: "sco_peerList",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rskj/sco-reputation-summary",
          label: "sco_reputationSummary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rskj/sco-unban-address",
          label: "sco_unbanAddress",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "web3",
      items: [
        {
          type: "doc",
          id: "rskj/web-3-client-version",
          label: "current client version",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rskj/web-3-sha-3",
          label: "Hashes data",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Schemas",
      items: [
        {
          type: "doc",
          id: "rskj/schemas/address",
          label: "address",
          className: "schema",
        },
        {
          type: "doc",
          id: "rskj/schemas/addressornull",
          label: "addressOrNull",
          className: "schema",
        },
        {
          type: "doc",
          id: "rskj/schemas/addresses",
          label: "addresses",
          className: "schema",
        },
        {
          type: "doc",
          id: "rskj/schemas/block",
          label: "Block",
          className: "schema",
        },
        {
          type: "doc",
          id: "rskj/schemas/blockexampleresultfulltransaction",
          label: "BlockExampleResultFullTransaction",
          className: "schema",
        },
        {
          type: "doc",
          id: "rskj/schemas/blockexampleresulttransactionhash",
          label: "BlockExampleResultTransactionHash",
          className: "schema",
        },
        {
          type: "doc",
          id: "rskj/schemas/blockhash",
          label: "blockHash",
          className: "schema",
        },
        {
          type: "doc",
          id: "rskj/schemas/blockhashornull",
          label: "blockHashOrNull",
          className: "schema",
        },
        {
          type: "doc",
          id: "rskj/schemas/integer-dec",
          label: "integer dec",
          className: "schema",
        },
        {
          type: "doc",
          id: "rskj/schemas/integer-hex",
          label: "integer hex",
          className: "schema",
        },
        {
          type: "doc",
          id: "rskj/schemas/blocknumberornull",
          label: "blockNumberOrNull",
          className: "schema",
        },
        {
          type: "doc",
          id: "rskj/schemas/blocknumbertag",
          label: "blockNumberTag",
          className: "schema",
        },
        {
          type: "doc",
          id: "rskj/schemas/blockornull",
          label: "blockOrNull",
          className: "schema",
        },
        {
          type: "doc",
          id: "rskj/schemas/blockref",
          label: "blockRef",
          className: "schema",
        },
        {
          type: "doc",
          id: "rskj/schemas/bloomfilter",
          label: "bloomFilter",
          className: "schema",
        },
        {
          type: "doc",
          id: "rskj/schemas/bytes",
          label: "bytes",
          className: "schema",
        },
        {
          type: "doc",
          id: "rskj/schemas/dataword",
          label: "dataWord",
          className: "schema",
        },
        {
          type: "doc",
          id: "rskj/schemas/to",
          label: "To",
          className: "schema",
        },
        {
          type: "doc",
          id: "rskj/schemas/dataword",
          label: "dataWord",
          className: "schema",
        },
        {
          type: "doc",
          id: "rskj/schemas/filterid",
          label: "filterId",
          className: "schema",
        },
        {
          type: "doc",
          id: "rskj/schemas/ip-address-or-block",
          label: "IP address or block",
          className: "schema",
        },
        {
          type: "doc",
          id: "rskj/schemas/ip-addresses",
          label: "IP addresses",
          className: "schema",
        },
        {
          type: "doc",
          id: "rskj/schemas/integer-dec",
          label: "integer dec",
          className: "schema",
        },
        {
          type: "doc",
          id: "rskj/schemas/integer-hex",
          label: "integer hex",
          className: "schema",
        },
        {
          type: "doc",
          id: "rskj/schemas/integerornull",
          label: "integerOrNull",
          className: "schema",
        },
        {
          type: "doc",
          id: "rskj/schemas/keccak",
          label: "keccak",
          className: "schema",
        },
        {
          type: "doc",
          id: "rskj/schemas/keccakorpending",
          label: "keccakOrPending",
          className: "schema",
        },
        {
          type: "doc",
          id: "rskj/schemas/log",
          label: "log",
          className: "schema",
        },
        {
          type: "doc",
          id: "rskj/schemas/logexampleresult",
          label: "LogExampleResult",
          className: "schema",
        },
        {
          type: "doc",
          id: "rskj/schemas/dataword",
          label: "dataWord",
          className: "schema",
        },
        {
          type: "doc",
          id: "rskj/schemas/node-id",
          label: "Node Id",
          className: "schema",
        },
        {
          type: "doc",
          id: "rskj/schemas/integer-hex",
          label: "integer hex",
          className: "schema",
        },
        {
          type: "doc",
          id: "rskj/schemas/nonceornull",
          label: "nonceOrNull",
          className: "schema",
        },
        {
          type: "doc",
          id: "rskj/schemas/null-value",
          label: "Null Value",
          className: "schema",
        },
        {
          type: "doc",
          id: "rskj/schemas/peer-scoring",
          label: "peer scoring",
          className: "schema",
        },
        {
          type: "doc",
          id: "rskj/schemas/position",
          label: "position",
          className: "schema",
        },
        {
          type: "doc",
          id: "rskj/schemas/dataword",
          label: "dataWord",
          className: "schema",
        },
        {
          type: "doc",
          id: "rskj/schemas/bytes",
          label: "bytes",
          className: "schema",
        },
        {
          type: "doc",
          id: "rskj/schemas/receipt",
          label: "receipt",
          className: "schema",
        },
        {
          type: "doc",
          id: "rskj/schemas/reputation-summary",
          label: "reputation summary",
          className: "schema",
        },
        {
          type: "doc",
          id: "rskj/schemas/scoringpeerlistexampleresult",
          label: "ScoringPeerListExampleResult",
          className: "schema",
        },
        {
          type: "doc",
          id: "rskj/schemas/dataword",
          label: "dataWord",
          className: "schema",
        },
        {
          type: "doc",
          id: "rskj/schemas/dataword",
          label: "dataWord",
          className: "schema",
        },
        {
          type: "doc",
          id: "rskj/schemas/logtopics",
          label: "LogTopics",
          className: "schema",
        },
        {
          type: "doc",
          id: "rskj/schemas/transaction",
          label: "transaction",
          className: "schema",
        },
        {
          type: "doc",
          id: "rskj/schemas/transaction",
          label: "transaction",
          className: "schema",
        },
        {
          type: "doc",
          id: "rskj/schemas/transactioncreateexampleparam",
          label: "TransactionCreateExampleParam",
          className: "schema",
        },
        {
          type: "doc",
          id: "rskj/schemas/transactionexampleresult",
          label: "TransactionExampleResult",
          className: "schema",
        },
        {
          type: "doc",
          id: "rskj/schemas/keccak",
          label: "keccak",
          className: "schema",
        },
        {
          type: "doc",
          id: "rskj/schemas/integerornull",
          label: "integerOrNull",
          className: "schema",
        },
        {
          type: "doc",
          id: "rskj/schemas/transactions",
          label: "transactions",
          className: "schema",
        },
      ],
    },
  ],
};

export default sidebar.apisidebar;
