import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  apisidebar: [
    {
      type: "doc",
      id: "rskj/rskj-json-rpc",
    },
    {
      type: "category",
      label: "eth",
      items: [
        {
          type: "doc",
          id: "rskj/eth-block-number",
          label: "Returns the number of most recent block.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rskj/eth-call",
          label: "Executes a new message call (locally) immediately without creating a transaction on the block chain.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rskj/eth-chain-id",
          label: "Returns the currently configured chain id",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rskj/eth-coinbase",
          label: "Returns the client coinbase address.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rskj/eth-estimate-gas",
          label: "Calculates an estimate of how much gas is necessary to allow the transaction to complete",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rskj/eth-gas-price",
          label: "Returns the current price per gas in wei",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rskj/eth-get-balance",
          label: "Returns the balance of the account of given address, 0 if not fo",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rskj/eth-get-block-by-hash",
          label: "Returns information about a block by hash",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rskj/eth-get-block-by-number",
          label: "Returns information about a block by block number",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rskj/eth-get-block-transaction-count-by-hash",
          label: "Returns the number of transactions in a block from a block matching the given block hash.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rskj/eth-get-block-transaction-count-by-number",
          label: "Returns the number of transactions in a block from a block matching the given block number.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rskj/eth-get-code",
          label: "Returns code at a given contract address",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rskj/eth-get-filter-changes",
          label: "Polling method for a filter, which returns an array of logs which occurred since last poll.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rskj/eth-get-filter-logs",
          label: "Returns an array of all logs matching filter with given id.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rskj/eth-get-logs",
          label: "Returns an array of all logs matching a given filter object.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rskj/eth-get-storage-at",
          label: "Gets a storage value from a contract address, a position, and an optional blockNumber",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rskj/eth-get-transaction-by-block-hash-and-index",
          label: "Returns information about a transaction by block hash and transaction index position.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rskj/eth-get-transaction-by-block-number-and-index",
          label: "Returns the information about a transaction requested by the block number and index of which it was mined.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rskj/eth-get-transaction-by-hash",
          label: "Returns the information about a transaction requested by transaction hash.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rskj/eth-get-transaction-count",
          label: "Returns the number of transactions `sent` from an address",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rskj/eth-get-transaction-receipt",
          label: "Returns the receipt information of a transaction by its hash.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rskj/eth-get-uncle-by-block-hash-and-index",
          label: "Returns information about a uncle of a block by hash and uncle index position.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rskj/eth-get-uncle-by-block-number-and-index",
          label: "Returns information about a uncle of a block by hash and uncle index position.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rskj/eth-get-uncle-count-by-block-hash",
          label: "Returns the number of uncles in a block from a block matching the given block hash.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rskj/eth-get-uncle-count-by-block-number",
          label: "Returns the number of uncles in a block from a block matching the given block number.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rskj/eth-hashrate",
          label: "Returns the number of hashes per second that the node is mining with.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rskj/eth-mining",
          label: "Returns true if client is actively mining new blocks.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rskj/eth-new-block-filter",
          label: "Creates a filter in the node, to notify when a new block arrives. To check if the state has changed, call eth_getFilterChanges.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rskj/eth-new-filter",
          label: "Creates a filter object, based on filter options, to notify when the state changes (logs).",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rskj/eth-new-pending-transaction-filter",
          label: "Creates a filter in the node, to notify when new pending transactions arrive.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rskj/eth-protocol-version",
          label: "Returns the current ethereum protocol version.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rskj/eth-send-raw-transaction",
          label: "Creates new message call transaction or a contract creation for signed transactions.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rskj/eth-send-transaction",
          label: "Creates new message call transaction or a contract creation, if the data field contains code.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rskj/eth-sign",
          label: "Calculates an Ethereum specific signature",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rskj/eth-syncing",
          label: "Returns an object with data about the sync status or false.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rskj/eth-uninstall-filter",
          label: "Uninstalls a filter with given id. Should always be called when watch is no longer needed.",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "mnr",
      items: [
        {
          type: "doc",
          id: "rskj/mnr-get-work",
          label: "Returns the hash of the current block, the seedHash, and the boundary condition to be met ('target').",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rskj/mnr-submit-work",
          label: "Used for submitting a proof-of-work solution.",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "net",
      items: [
        {
          type: "doc",
          id: "rskj/net-listening",
          label: "Returns client listening status",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rskj/net-peer-count",
          label: "Number of peers",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rskj/net-peer-list",
          label: "List of peers",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rskj/net-version",
          label: "Network identifier associated with network",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "sco",
      items: [
        {
          type: "doc",
          id: "rskj/sco-ban-address",
          label: "Adds an address (or block of addresses) to the list of banned addresses",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rskj/sco-banned-addresses",
          label: "Returns the list of banned addresses and blocks of addresses",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rskj/sco-clear-peer-scoring",
          label: "Clears scoring records for the given peer id",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rskj/sco-peer-list",
          label: "Returns the collected peer scoring information",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rskj/sco-reputation-summary",
          label: "Generates a reputation summary (all peers aggregated)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rskj/sco-unban-address",
          label: "Removes an address (or block of addresses) from the list of banned addresses",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "web3",
      items: [
        {
          type: "doc",
          id: "rskj/web-3-client-version",
          label: "current client version",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rskj/web-3-sha-3",
          label: "Hashes data",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Schemas",
      items: [
        {
          type: "doc",
          id: "rskj/schemas/address",
          label: "address",
          className: "schema",
        },
        {
          type: "doc",
          id: "rskj/schemas/addressornull",
          label: "addressOrNull",
          className: "schema",
        },
        {
          type: "doc",
          id: "rskj/schemas/addresses",
          label: "addresses",
          className: "schema",
        },
        {
          type: "doc",
          id: "rskj/schemas/block",
          label: "Block",
          className: "schema",
        },
        {
          type: "doc",
          id: "rskj/schemas/blockexampleresultfulltransaction",
          label: "BlockExampleResultFullTransaction",
          className: "schema",
        },
        {
          type: "doc",
          id: "rskj/schemas/blockexampleresulttransactionhash",
          label: "BlockExampleResultTransactionHash",
          className: "schema",
        },
        {
          type: "doc",
          id: "rskj/schemas/blockhash",
          label: "blockHash",
          className: "schema",
        },
        {
          type: "doc",
          id: "rskj/schemas/blockhashornull",
          label: "blockHashOrNull",
          className: "schema",
        },
        {
          type: "doc",
          id: "rskj/schemas/integer-dec",
          label: "integer dec",
          className: "schema",
        },
        {
          type: "doc",
          id: "rskj/schemas/integer-hex",
          label: "integer hex",
          className: "schema",
        },
        {
          type: "doc",
          id: "rskj/schemas/blocknumberornull",
          label: "blockNumberOrNull",
          className: "schema",
        },
        {
          type: "doc",
          id: "rskj/schemas/blocknumbertag",
          label: "blockNumberTag",
          className: "schema",
        },
        {
          type: "doc",
          id: "rskj/schemas/blockornull",
          label: "blockOrNull",
          className: "schema",
        },
        {
          type: "doc",
          id: "rskj/schemas/blockref",
          label: "blockRef",
          className: "schema",
        },
        {
          type: "doc",
          id: "rskj/schemas/bloomfilter",
          label: "bloomFilter",
          className: "schema",
        },
        {
          type: "doc",
          id: "rskj/schemas/bytes",
          label: "bytes",
          className: "schema",
        },
        {
          type: "doc",
          id: "rskj/schemas/dataword",
          label: "dataWord",
          className: "schema",
        },
        {
          type: "doc",
          id: "rskj/schemas/to",
          label: "To",
          className: "schema",
        },
        {
          type: "doc",
          id: "rskj/schemas/dataword",
          label: "dataWord",
          className: "schema",
        },
        {
          type: "doc",
          id: "rskj/schemas/filterid",
          label: "filterId",
          className: "schema",
        },
        {
          type: "doc",
          id: "rskj/schemas/ip-address-or-block",
          label: "IP address or block",
          className: "schema",
        },
        {
          type: "doc",
          id: "rskj/schemas/ip-addresses",
          label: "IP addresses",
          className: "schema",
        },
        {
          type: "doc",
          id: "rskj/schemas/integer-dec",
          label: "integer dec",
          className: "schema",
        },
        {
          type: "doc",
          id: "rskj/schemas/integer-hex",
          label: "integer hex",
          className: "schema",
        },
        {
          type: "doc",
          id: "rskj/schemas/integerornull",
          label: "integerOrNull",
          className: "schema",
        },
        {
          type: "doc",
          id: "rskj/schemas/keccak",
          label: "keccak",
          className: "schema",
        },
        {
          type: "doc",
          id: "rskj/schemas/keccakorpending",
          label: "keccakOrPending",
          className: "schema",
        },
        {
          type: "doc",
          id: "rskj/schemas/log",
          label: "log",
          className: "schema",
        },
        {
          type: "doc",
          id: "rskj/schemas/logexampleresult",
          label: "LogExampleResult",
          className: "schema",
        },
        {
          type: "doc",
          id: "rskj/schemas/dataword",
          label: "dataWord",
          className: "schema",
        },
        {
          type: "doc",
          id: "rskj/schemas/node-id",
          label: "Node Id",
          className: "schema",
        },
        {
          type: "doc",
          id: "rskj/schemas/integer-hex",
          label: "integer hex",
          className: "schema",
        },
        {
          type: "doc",
          id: "rskj/schemas/nonceornull",
          label: "nonceOrNull",
          className: "schema",
        },
        {
          type: "doc",
          id: "rskj/schemas/null-value",
          label: "Null Value",
          className: "schema",
        },
        {
          type: "doc",
          id: "rskj/schemas/peer-scoring",
          label: "peer scoring",
          className: "schema",
        },
        {
          type: "doc",
          id: "rskj/schemas/position",
          label: "position",
          className: "schema",
        },
        {
          type: "doc",
          id: "rskj/schemas/dataword",
          label: "dataWord",
          className: "schema",
        },
        {
          type: "doc",
          id: "rskj/schemas/bytes",
          label: "bytes",
          className: "schema",
        },
        {
          type: "doc",
          id: "rskj/schemas/receipt",
          label: "receipt",
          className: "schema",
        },
        {
          type: "doc",
          id: "rskj/schemas/reputation-summary",
          label: "reputation summary",
          className: "schema",
        },
        {
          type: "doc",
          id: "rskj/schemas/scoringpeerlistexampleresult",
          label: "ScoringPeerListExampleResult",
          className: "schema",
        },
        {
          type: "doc",
          id: "rskj/schemas/dataword",
          label: "dataWord",
          className: "schema",
        },
        {
          type: "doc",
          id: "rskj/schemas/dataword",
          label: "dataWord",
          className: "schema",
        },
        {
          type: "doc",
          id: "rskj/schemas/logtopics",
          label: "LogTopics",
          className: "schema",
        },
        {
          type: "doc",
          id: "rskj/schemas/transaction",
          label: "transaction",
          className: "schema",
        },
        {
          type: "doc",
          id: "rskj/schemas/transaction",
          label: "transaction",
          className: "schema",
        },
        {
          type: "doc",
          id: "rskj/schemas/transactioncreateexampleparam",
          label: "TransactionCreateExampleParam",
          className: "schema",
        },
        {
          type: "doc",
          id: "rskj/schemas/transactionexampleresult",
          label: "TransactionExampleResult",
          className: "schema",
        },
        {
          type: "doc",
          id: "rskj/schemas/keccak",
          label: "keccak",
          className: "schema",
        },
        {
          type: "doc",
          id: "rskj/schemas/integerornull",
          label: "integerOrNull",
          className: "schema",
        },
        {
          type: "doc",
          id: "rskj/schemas/transactions",
          label: "transactions",
          className: "schema",
        },
      ],
    },
  ],
};

export default sidebar.apisidebar;
